//
//  StudyLLMBackend.swift
//  SmartStudyPlanner
//
//  Created by Pubudu Perera on 2026-05-06.
//

import Foundation
import FoundationModels

// Used by StudyContentOrchestrator in the subject workspace.
// It hides whether study paths and quizzes are generated by Apple Foundation Models or the hosted fallback server.
struct GeneratedStudyPath {
    struct Topic {
        let order: Int
        let title: String
        let description: String
        let subtopics: [String]
        let weightPercent: Int
        let difficultyLevel: Int
        let estimatedMinutes: Int
    }
    let topics: [Topic]
}

struct GeneratedQuiz {
    struct Item {
        let question: String
        let answer: String
        let keyword: String
    }
    let items: [Item]
}

public struct QuizMCQItem {
    public let questionText: String
    public let options: [String]
    public let correctOptionIndex: Int
    public let category: String
    public let expertTip: String
    public let keyword: String
    
    public init(questionText: String, options: [String], correctOptionIndex: Int, category: String, expertTip: String, keyword: String) {
        self.questionText = questionText
        self.options = options
        self.correctOptionIndex = correctOptionIndex
        self.category = category
        self.expertTip = expertTip
        self.keyword = keyword
    }
}

public struct QuizGenerationResult {
    public let questions: [QuizMCQItem]
    
    public init(questions: [QuizMCQItem]) {
        self.questions = questions
    }
}

protocol StudyLLMBackend {
    func generateStudyPath(from text: String, topicCount: Int) async throws -> GeneratedStudyPath
    func generateQuiz(from text: String, questionCount: Int) async throws -> GeneratedQuiz
    func generateQuizQuestions(from text: String, questionCount: Int, category: String) async throws -> QuizGenerationResult
}

enum LLMBackendSelector {
    // Prefer on-device Foundation Models when available; otherwise call the hosted LLM endpoint.
    static func resolve(hostedURL: URL) -> StudyLLMBackend {
        if case .available = SystemLanguageModel.default.availability {
            print("[LLM] Using FoundationModels (Apple Intelligence)")
            return FoundationModelsBackend()
        }
        print("[LLM] FoundationModels unavailable — falling back to hosted LLM at \(hostedURL)")
        return HostedLLMBackend(serverURL: hostedURL)
    }
}
